applications:
  # - name: namespaces
  #   wave: -100

  - name: istio-base
    namespace: istio
    wave: -90

global:
  namespace: argocd

  finalizers:
    - resources-finalizer.argocd.argoproj.io

  destination:
    namespace: default
    name: in-cluster

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
