---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: newrelic
spec:
  refreshInterval: 1h0m0s

  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-subscription-key-vault

  target:
    name: newrelic
    creationPolicy: Owner

  data:
    - secretKey: licenseKey
      remoteRef:
        key: secret/new-relic-license-key
