#!/bin/bash

echo ""
echo "1. Create an AKS Cluster with Azure Application Gateway"
echo ""
echo "1.1. Provisioning"
echo ""

stackrun ${STACK_AKS_IMAGE_NAME?} \
  apply -auto-approve -no-color

SCRIPT_RESULT=$?; [ "${SCRIPT_RESULT}" -eq "0" ] && echo "OK" || exit "${SCRIPT_RESULT}"

echo ""
echo "1.2. Retrieve Credentials"
echo ""

env \
  DEBUG=0 \
  stackrun ${STACK_AKS_IMAGE_NAME?} \
    output -raw kubeconfig > ~/.kube/config

SCRIPT_RESULT=$?; [ "${SCRIPT_RESULT}" -eq "0" ] && echo "OK" || exit "${SCRIPT_RESULT}"

chmod 0600 ~/.kube/config

echo ""
echo "1.3. Connection Test"
echo ""

kubectl get namespaces

SCRIPT_RESULT=$?; [ "${SCRIPT_RESULT}" -eq "0" ] && echo "OK" || exit "${SCRIPT_RESULT}"
