#!/bin/bash
helm repo add --force-update external-secrets https://charts.external-secrets.io &> /dev/null
helm repo update external-secrets &> /dev/null
helm search repo external-secrets

helm upgrade \
  --install \
  --namespace external-secrets \
  --create-namespace \
  external-secrets external-secrets/external-secrets \
  --wait

# Service Principal
ARM_CLIENT_ID_BASE64=$(     echo ${ARM_CLIENT_ID?}     | base64 )
ARM_CLIENT_SECRET_BASE64=$( echo ${ARM_CLIENT_SECRET?} | base64 )

cat <<EOF | kubectl --namespace external-secrets apply -f -
---
apiVersion: v1
kind: Secret
metadata:
  name: azurerm-service-principal
type: Opaque
data:
  ARM_CLIENT_ID: ${ARM_CLIENT_ID_BASE64}
  ARM_CLIENT_SECRET: ${ARM_CLIENT_SECRET_BASE64}
---
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: azure-subscription-key-vault
spec:
  provider:
    azurekv:
      authType: ServicePrincipal

      tenantId: ${ARM_TENANT_ID}
      vaultUrl: https://${ARM_KEYVAULT_NAME}.vault.azure.net

      authSecretRef:
        clientId:
          key: ARM_CLIENT_ID
          name: azurerm-service-principal
          namespace: external-secrets

        clientSecret:
          key: ARM_CLIENT_SECRET
          name: azurerm-service-principal
          namespace: external-secrets
EOF
