#!/bin/bash

echo ""
echo "2. Install AAD Pod Identity with RBAC"
echo ""

kubectl \
  apply \
  -f https://raw.githubusercontent.com/Azure/aad-pod-identity/v1.6.0/deploy/infra/deployment-rbac.yaml

SCRIPT_RESULT=$?; [ "${SCRIPT_RESULT}" -eq "0" ] && echo "OK" || exit "${SCRIPT_RESULT}"
