#!/bin/bash

echo ""
echo "3. Install AGIC: Application Gateway Ingress Controller"
echo ""
echo "3.1. Retrieve Stack Outputs"
echo ""

env \
  DEBUG=0 \
  stackrun ${STACK_AKS_IMAGE_NAME?} \
    output -json > "${STACK_AKS_OUTPUT_FILE?}"

SCRIPT_RESULT=$?; [ "${SCRIPT_RESULT}" -eq "0" ] && echo "OK" || exit "${SCRIPT_RESULT}"

export MANAGED_IDENTITY_ID="$(                    jq -r .kubelet_identity_id.value                     "${STACK_AKS_OUTPUT_FILE?}")"
export MANAGED_IDENTITY_CLIENT_ID="$(             jq -r .kubelet_identity_client_id.value              "${STACK_AKS_OUTPUT_FILE?}")"
export APPLICATION_GATEWAY_ID="$(                 jq -r .application_gateway_id.value                  "${STACK_AKS_OUTPUT_FILE?}")"
export APPLICATION_GATEWAY_NAME="$(               jq -r .application_gateway_name.value                "${STACK_AKS_OUTPUT_FILE?}")"
export APPLICATION_GATEWAY_RESOURCE_GROUP_NAME="$(jq -r .application_gateway_resource_group_name.value "${STACK_AKS_OUTPUT_FILE?}")"

echo ""
echo "3.2. Install using Helm"
echo ""

helm repo add    application-gateway-kubernetes-ingress https://appgwingress.blob.core.windows.net/ingress-azure-helm-package/ &> /dev/null
helm repo update application-gateway-kubernetes-ingress &> /dev/null
helm search repo application-gateway-kubernetes-ingress

echo ""
echo "appgw:"
echo "  subscriptionId:     ${ARM_SUBSCRIPTION_ID?}"
echo "  resourceGroup:      ${APPLICATION_GATEWAY_RESOURCE_GROUP_NAME?}"
echo "  name:               ${APPLICATION_GATEWAY_NAME?}"
echo ""
echo "armAuth:"
echo "  type:               aadPodIdentity"
echo "  identityResourceID: ${MANAGED_IDENTITY_ID?}"
echo "  identityClientID:   ${MANAGED_IDENTITY_CLIENT_ID?}"
echo ""

helm upgrade \
  --install ingress-azure \
  --set "appgw.subscriptionId=${ARM_SUBSCRIPTION_ID?}" \
  --set "appgw.resourceGroup=${APPLICATION_GATEWAY_RESOURCE_GROUP_NAME?}" \
  --set "appgw.name=${APPLICATION_GATEWAY_NAME?}" \
  --set "armAuth.type=aadPodIdentity" \
  --set "armAuth.identityResourceID=${MANAGED_IDENTITY_ID?}" \
  --set "armAuth.identityClientID=${MANAGED_IDENTITY_CLIENT_ID?}" \
  --set "rbac.enabled=true" \
  application-gateway-kubernetes-ingress/ingress-azure \
  --wait

echo ""
echo "3.3. Show logs"
echo ""

kubectl logs -l app=ingress-azure
