#!/bin/bash
kubectl create namespace external-dns

kubectl --namespace external-dns apply -f - <<EOF
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: azure-config-file
spec:
  refreshInterval: 1h
  
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-subscription-key-vault

  target:
    name: azure-config-file

    creationPolicy: Owner
    
    template:
      type: Opaque

      data:
        azure-config-file.json: |
          {
            "tenantId": "{{ .tenantId | toString }}",
            "subscriptionId": "{{ .subscriptionId | toString }}",
            "resourceGroup": "{{ .resourceGroup | toString }}",
            "aadClientId": "{{ .aadClientId | toString }}",
            "aadClientSecret": "{{ .aadClientSecret | toString }}"
          }

  data:
    - secretKey: "tenantId"
      remoteRef:
        key: secret/arm-tenant-id

    - secretKey: "subscriptionId"
      remoteRef:
        key: secret/arm-subscription-id

    - secretKey: "resourceGroup"
      remoteRef:
        key: secret/arm-dns-zone-resource-group

    - secretKey: "aadClientId"
      remoteRef:
        key: secret/arm-client-id

    - secretKey: "aadClientSecret"
      remoteRef:
        key: secret/arm-client-secret
EOF

helm repo add external-dns https://kubernetes-sigs.github.io/external-dns/ &> /dev/null
helm repo update external-dns &> /dev/null
helm search repo external-dns

EXTERNAL_DNS_VALUES_FILE="${HOME}/.helm/external-dns/values.yaml"

mkdir -p "$(dirname ${EXTERNAL_DNS_VALUES_FILE?})"

cat <<EOF > "${EXTERNAL_DNS_VALUES_FILE?}"
provider: azure

extraVolumes:
  - name: azure-config-file
    secret:
      secretName: azure-config-file
      items:
        - key: azure-config-file.json
          path: azure.json

extraVolumeMounts:
  - name: azure-config-file
    mountPath: /etc/kubernetes
    readOnly: true
EOF

helm upgrade \
  --install \
  --namespace external-dns \
  external-dns external-dns/external-dns \
  --values "${EXTERNAL_DNS_VALUES_FILE}" \
  --wait
