#!/bin/bash

echo ""
echo "4. Install httpbin"
echo ""
echo "4.1. Install using Helm Chart"
echo ""

# HTTPBIN_HOST="wasp-sbx-na-eus2-blue.eastus2.cloudapp.azure.com"
HTTPBIN_HOST="echo.eastus2.sandbox.wasp.silvios.me"
HTTPBIN_NAMESPACE="httpbin"
INGRESS_NAME="httpbin"
INGRESS_CLASS_NAME="azure-application-gateway"

echo "httpbin:"
echo "  ingress:"
echo "    host:          ${HTTPBIN_HOST?}"
echo "    class:         ${INGRESS_CLASS_NAME?}"
echo ""

helm upgrade \
  --install \
  --namespace ${HTTPBIN_NAMESPACE?} \
  --create-namespace \
  httpbin ./charts/httpbin/ \
  --set "ingress.enabled=true" \
  --set "ingress.className=${INGRESS_CLASS_NAME?}" \
  --set "ingress.hosts[0].host=${HTTPBIN_HOST?}" \
  --set "ingress.hosts[0].paths[0].path=/" \
  --set "ingress.hosts[0].paths[0].pathType=ImplementationSpecific" \
  --wait

echo ""
echo "4.2. Wait for Ingress IP"
echo ""

APPLICATION_INGRESS_PUBLIC_IP="$(wait_for_ingress_ip \
  "${HTTPBIN_NAMESPACE?}" \
  "${INGRESS_NAME?}")"

echo "${APPLICATION_INGRESS_PUBLIC_IP}"

echo ""
echo "4.3. Test with curl"
echo ""

APPLICATION_GATEWAY_URL="http://${HTTPBIN_HOST}"

HTTP_CODE="000"

while [ "${HTTP_CODE}" != "200" ]; do
  HTTP_CODE=$(curl \
    --silent \
    --output /dev/null \
    --write-out "%{http_code}" \
      ${APPLICATION_GATEWAY_URL})
  
  sleep 3
done

curl \
  --head \
  --silent ${APPLICATION_GATEWAY_URL}/get
