#!/bin/bash

echo ""
echo "4. Install httpbin (TLS Ingress Enabled)"
echo ""
echo "4.1. Install using Helm Chart"
echo ""

HTTPBIN_HOST="echo.eastus2.sandbox.wasp.silvios.me"
HTTPBIN_NAMESPACE="httpbin"
INGRESS_NAME="httpbin"
INGRESS_CLASS_NAME="azure-application-gateway"
INGRESS_TLS_SECRET_NAME="httpbin-tls-ingress"
CERT_MANAGER_CLUSTER_ISSUER="letsencrypt-staging-application-gateway"

echo "httpbin:"
echo "  ingress:"
echo "    host:          ${HTTPBIN_HOST?}"
echo "    class:         ${INGRESS_CLASS_NAME?}"
echo "    tlsSecret:     ${INGRESS_TLS_SECRET_NAME?}"
echo "    clusterIssuer: ${CERT_MANAGER_CLUSTER_ISSUER?}"
echo ""

helm upgrade \
  --install \
  --namespace httpbin \
  --create-namespace \
  httpbin ./charts/httpbin/ \
  --set "ingress.enabled=true" \
  --set "ingress.className=${INGRESS_CLASS_NAME?}" \
  --set "ingress.annotations.cert-manager\.io/cluster-issuer=${CERT_MANAGER_CLUSTER_ISSUER?}" \
  --set "ingress.hosts[0].host=${HTTPBIN_HOST?}" \
  --set "ingress.hosts[0].paths[0].path=/" \
  --set "ingress.hosts[0].paths[0].pathType=ImplementationSpecific" \
  --set "ingress.tls[0].secretName=${INGRESS_TLS_SECRET_NAME?}" \
  --set "ingress.tls[0].hosts[0]=${HTTPBIN_HOST?}"

echo ""

kubectl -n ${HTTPBIN_NAMESPACE?} get ingress ${INGRESS_NAME?}

echo ""
echo "4.2. Wait for Ingress IP"
echo ""

APPLICATION_INGRESS_PUBLIC_IP="$(wait_for_ingress_ip \
  "${HTTPBIN_NAMESPACE?}" \
  "${INGRESS_NAME?}")"

echo "${APPLICATION_INGRESS_PUBLIC_IP}"
echo ""
