#!/bin/bash

NAMESPACE=$1
INGRESS_NAME=$2

APPLICATION_INGRESS_PUBLIC_IP=""

while [ -z "${APPLICATION_INGRESS_PUBLIC_IP}" ]; do
  APPLICATION_INGRESS_PUBLIC_IP="$(kubectl \
    --namespace ${NAMESPACE?} get Ingress ${INGRESS_NAME?} \
    --template="{{range .status.loadBalancer.ingress}}{{.ip}}{{end}}")"

  if [ -z "${APPLICATION_INGRESS_PUBLIC_IP}" ]; then
    sleep 2
  else
    echo "${APPLICATION_INGRESS_PUBLIC_IP}"
  fi
done
