ingress-nginx:
  controller:
    service:
      type: NodePort # Kind
    nodeSelector:
      ingress-ready: "true"
    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
