ingress-nginx:
  defaultBackend:
    enabled: false

  controller:
    config:
      proxy-buffer-size: "128k"

    podAnnotations:
      sidecar.istio.io/inject: "false"

    service:
      type: LoadBalancer
      externalTrafficPolicy: "Local"
      annotations:
        silvios.me/enviroment-id: "sbx"
