apiVersion: v2
appVersion: 0.2.0
dependencies:
- name: common-library
  repository: https://helm-charts.newrelic.com
  version: 1.1.0
description: A Helm chart to deploy the New Relic Kubernetes Metrics Adapter.
home: https://hub.docker.com/r/newrelic/newrelic-k8s-metrics-adapter
icon: https://newrelic.com/assets/newrelic/source/NewRelic-logo-square.svg
keywords:
- infrastructure
- newrelic
- monitoring
maintainers:
- name: alvarocabanas
- name: carlossscastro
- name: gsanchezgavier
- name: kang-makes
- name: marcsanmi
- name: paologallinaharbur
- name: roobre
- name: sigilioso
name: newrelic-k8s-metrics-adapter
sources:
- https://github.com/newrelic/newrelic-k8s-metrics-adapter
- https://github.com/newrelic/newrelic-k8s-metrics-adapter/tree/main/charts/newrelic-k8s-metrics-adapter
version: 0.7.12
