---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: inbound
spec:
  selector:
    istio: gateway

  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP

      hosts:
        - "*.silvios.me"
        - "*.cloudapp.azure.com"
