---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  annotations:
  {{- with .Values.annotations.ingress }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
      {{- range $host := .Values.hosts }}
        - {{ . }}
      {{- end }}
      secretName: ingress-tls-{{ .Values.name }}-selfsigned
  rules:
  {{- range $host := .Values.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /api/*
            backend:
              service:
                name: istio-gateway
                port:
                  number: 80
            pathType: ImplementationSpecific

          - path: /
            backend:
              service:
                name: istio-gateway
                port:
                  number: 80
            pathType: ImplementationSpecific
  {{- end }}
