{{- if eq .Values.global.environment.cluster.ingress.type "nginx" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: istio
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.global.environment.cluster.certificates.type }}-{{ .Values.global.environment.cluster.certificates.server }}-{{ .Values.global.environment.cluster.ingress.type }}
    external-dns.alpha.kubernetes.io/ttl: 1m
spec:
  ingressClassName: "nginx"

  tls:
    - hosts:
        - services.{{ .Values.global.environment.id }}.{{ .Values.global.environment.domain }}
      secretName: ingress-tls-istio

  rules:
    - host: services.{{ .Values.global.environment.id }}.{{ .Values.global.environment.domain }}
      http:
        paths:
          - path: /api/*
            backend:
              service:
                name: istio-gateway
                port:
                  number: 80
            pathType: ImplementationSpecific

          - path: /
            backend:
              service:
                name: istio-gateway
                port:
                  number: 80
            pathType: ImplementationSpecific
{{- end }}
