{{- if eq .Values.ingress.type "azure" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: istio
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: azure/application-gateway
    cert-manager.io/cluster-issuer: letsencrypt-application-gateway-staging
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
    appgw.ingress.kubernetes.io/request-timeout: "70"
    external-dns.alpha.kubernetes.io/ttl: 1m
spec:
  tls:
    - hosts:
        - services.{{ .Values.global.environment.id }}.{{ .Values.global.environment.domain }}
      secretName: ingress-tls-istio

  rules:
    - host: services.{{ .Values.global.environment.id }}.{{ .Values.global.environment.domain }}
      http:
        paths:
          - path: /api/*
            backend:
              service:
                name: istio-gateway
                port:
                  number: 80
            pathType: ImplementationSpecific

          - path: /
            backend:
              service:
                name: istio-gateway
                port:
                  number: 80
            pathType: ImplementationSpecific
{{- end }}
