apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  
  {{- if $.Values.global }}
  {{- with $.Values.global.environment.argocd }}
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: "{{ .cname }}"
  {{- end }}
  {{- end }}
spec:
  type: LoadBalancer
  
  selector:
    app.kubernetes.io/name: argocd-server
  
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080

    - name: https
      port: 443
      protocol: TCP
      targetPort: 8080
