server:
  additionalApplications:
    - name: httpbin
      additionalLabels: {}
      additionalAnnotations: {}
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      project: default
      source:
        targetRevision: HEAD
        repoURL: git@github.com:smsilva/wasp-gitops.git
        path: charts/httpbin
      destination:
        name: in-cluster
        namespace: httpbin
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
