server:
  extraArgs:
    - --insecure
  ingress:
    enabled: true
    https: false
    hosts:
      - ${ARGOCD_HOST}
    pathType: ImplementationSpecific
    paths:
      - /
      - /argocd
    tls:
      - secretName: ${ARGOCD_TLS_SECRET}
        hosts:
          - ${ARGOCD_HOST}
    annotations:
      kubernetes.io/ingress.class: "${INGRESS_CLASS_NAME}"
      appgw.ingress.kubernetes.io/backend-protocol: "http"
      cert-manager.io/cluster-issuer: ${CERT_MANAGER_CLUSTER_ISSUER}
