server:
  additionalProjects:
    - name: infra
      description: Infrastructure
      sourceRepos:
        - git@github.com:smsilva/wasp-gitops.git
      destinations:
        - name: in-cluster
          namespace: '*'
          server: '*'
      namespaceResourceWhitelist:
        - group: '*'
          kind: '*'
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'
