fullnameOverride: "argocd"
server:
  extraArgs:
    - --insecure
  ingress:
    enabled: true
    https: false
    ingressClassName: "${INGRESS_CLASS_NAME}"
    hosts:
      - ${ARGOCD_HOST}
    pathType: ImplementationSpecific
    paths:
      - /
      - /argocd
    tls:
      - secretName: ${ARGOCD_TLS_SECRET}
        hosts:
          - ${ARGOCD_HOST}
    annotations:
      appgw.ingress.kubernetes.io/backend-protocol: "http"
      cert-manager.io/cluster-issuer: ${CERT_MANAGER_CLUSTER_ISSUER}
  config:
    url: https://${ARGOCD_HOST}
    users.anonymous.enabled: "false"
    admin.enabled: "false"
    oidc.config: |
      name: AzureAD
      issuer: https://login.microsoftonline.com/${ARM_TENANT_ID}/v2.0
      clientID: ${ARGOCD_APP_REGISTRATION_ID}
      clientSecret: ${DOLLAR}oidc.azuread.clientSecret
      requestedIDTokenClaims:
        groups:
          essential: true
      requestedScopes:
        - openid
        - profile
        - email
  rbacConfig:
    policy.csv: |
      p, role:app-contributor, applications, delete, default/*, allow
      p, role:app-contributor, applications, get, default/*, allow
      p, role:app-contributor, applications, sync, default/*, allow
      p, role:app-contributor, applications, action/apps/Deployment/restart*, default/*, allow
      g, "${ARGOCD_GROUP_CONTRIBUTOR}", role:app-contributor
      g, "${ARGOCD_GROUP_CONTRIBUTOR}", role:readonly
      g, "${ARGOCD_GROUP_ADMIN}", role:admin
    policy.default: role:empty
  additionalApplications:
    - name: httpbin
      namespace: ${ARGOCD_NAMESPACE}
      additionalLabels: {}
      additionalAnnotations: {}
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      project: default
      source:
        targetRevision: HEAD
        repoURL: git@github.com:smsilva/wasp-gitops.git
        path: charts/httpbin
      destination:
        name: in-cluster
        namespace: httpbin
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
