server:
  additionalProjects:
    - name: infra
      description: Infrastructure
      sourceRepos:
        - https://github.com/smsilva/wasp-gitops
      destinations:
        - name: in-cluster
          namespace: '*'
          server: '*'
      namespaceResourceWhitelist:
        - group: '*'
          kind: '*'
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'
