---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: argocd-repo-creds-github
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-subscription-key-vault

  target:
    name: argocd-repo-creds-github
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          managed-by: argocd.argoproj.io
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      type: Opaque
      data:
        sshPrivateKey: |
          {{ .idrsabase64filecontent | base64decode | toString }}
        url: |
          {{ .privaterepourl | toString }}

  data:
    - secretKey: "idrsabase64filecontent"
      remoteRef:
        key: secret/argocd-repo-creds-base64-encoded-private-key-github

    - secretKey: "privaterepourl"
      remoteRef:
        key: secret/argocd-repo-creds-url-github
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: argocd-repository-github
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-subscription-key-vault

  target:
    name: argocd-repository-github
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          managed-by: argocd.argoproj.io
        labels:
          argocd.argoproj.io/secret-type: repository
      type: Opaque

  data:
    - secretKey: "name"
      remoteRef:
        key: secret/argocd-repository-github-name

    - secretKey: "project"
      remoteRef:
        key: secret/argocd-repository-github-project

    - secretKey: "type"
      remoteRef:
        key: secret/argocd-repository-github-type

    - secretKey: "url"
      remoteRef:
        key: secret/argocd-repository-github-url
