extraObjects:
  - apiVersion: external-secrets.io/v1alpha1
    kind: ExternalSecret
    metadata:
      name: argocd-secret
    spec:
      refreshInterval: 1h
      secretStoreRef:
        kind: ClusterSecretStore
        name: azure-subscription-key-vault
    
      target:
        name: argocd-secret
        creationPolicy: Merge

      data:
        - secretKey: "oidc.azuread.clientSecret"
          remoteRef:
            key: secret/argocd-oidc-azuread-client-secret
