---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-app-gw-staging
spec:
  acme:
    email: smsilva@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-app-gw-staging-issuer-account-key
    solvers:
      - http01:
          ingress:
            class: azure-application-gateway
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-app-gw-prod
spec:
  acme:
    email: smsilva@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-app-gw-prod-issuer-account-key
    solvers:
      - http01:
          ingress:
            class: azure-application-gateway
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-nginx-staging
spec:
  acme:
    email: smsilva@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-nginx-staging-issuer-account-key
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-nginx-prod
spec:
  acme:
    email: smsilva@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-nginx-prod-issuer-account-key
    solvers:
      - http01:
          ingress:
            class: nginx
