applications:
  - name: namespaces
    wave: 10

  - name: nri-bundle-foundation
    namespace: newrelic
    wave: 10

  - name: nri-bundle
    namespace: newrelic
    wave: 20

  - name: istio-base
    namespace: istio-system
    wave: 20

  - name: istio-control-plane
    namespace: istio-system
    wave: 30

  - name: istio-gateway
    namespace: istio-ingress
    wave: 40

  - name: httpbin
    namespace: httpbin
    wave: 40
