environment:
  id: undefined-id
  domain: undefined-domain.io
  cluster:
    name: undefined-cluster-name
    ingress:
      type: nginx

finalizers:
  - resources-finalizer.argocd.argoproj.io

project: infra

source:
  repoURL: git@github.com:smsilva/wasp-gitops.git
  targetRevision: HEAD

destination:
  namespace: default
  name: in-cluster

syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true

applications:
  - name: namespaces
    wave: 10

ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
      - /status

  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jsonPointers:
      - /webhooks/0/namespaceSelector/matchExpressions/2
    jqPathExpressions:
      - '.webhooks[]?.failurePolicy'

  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
      - '.webhooks[]?.clientConfig.caBundle'
      - '.webhooks[]?.namespaceSelector.matchExpressions'
