---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.olmOperatorNamespace }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: global-operators
  namespace: {{ .Values.olmOperatorNamespace }}
