---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pl-deleter-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pl-deleter-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pl-deleter-role
subjects:
- kind: ServiceAccount
  name: pl-deleter-service-account
  namespace: "{{ .Release.Namespace }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pl-deleter-role
rules:
# Allow actions on Kubernetes objects
- apiGroups:
  - ""
  - apps
  - rbac.authorization.k8s.io
  - extensions
  - etcd.database.coreos.com
  - batch
  - nats.io
  - policy
  resources:
  - clusterroles
  - clusterrolebindings
  - configmaps
  - secrets
  - pods
  - services
  - deployments
  - daemonsets
  - persistentvolumes
  - persistentvolumeclaims
  - roles
  - rolebindings
  - serviceaccounts
  - etcdclusters
  - statefulsets
  - cronjobs
  - jobs
  - natsclusters
  - podsecuritypolicies
  verbs: ["*"]
