name: $(Date:yyyy-MM-dd)$(Rev:.r)

trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name:    environment
    type:    string
    default: wasp-sbx-na

variables:
  - template: vars/global.yaml
  - group: azure-credentials-wasp-sandbox

steps:
  - script: |
      AGENT_PATH=${PATH}:$(Agent.TempDirectory)/terraform-packager/scripts

      echo "[INFO] Build.BuildId........: $(Build.BuildId)"
      echo "[INFO] Build.BuildNumber....: $(Build.BuildNumber)"
      echo "[INFO] Build.DefinitionName.: $(Build.DefinitionName)"
      echo "[INFO] Environment..........: ${ENVIRONMENT_NAME}"

      echo "##vso[task.setvariable variable=PATH]${AGENT_PATH}"
    displayName: 'Parameters'
    env:
      ENVIRONMENT_NAME: ${{ parameters.environment }}

  - script: |
      git clone https://github.com/smsilva/terraform-packager.git $(Agent.TempDirectory)/terraform-packager
    displayName: "Clone Terraform Packager"

  - script: |
      env \
        STACK_INSTANCE_NAME=${ENVIRONMENT_NAME} \
        DEBUG=2 \
          stackrun silviosilva/azure-wasp-foundation:0.1.0 apply \
          -auto-approve \
          -var="name=${ENVIRONMENT_NAME}"

    displayName: 'Environment Stack'
    env:
      ENVIRONMENT_NAME:  ${{ parameters.environment }}
      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
      ARM_ACCESS_KEY:    $(ARM_ACCESS_KEY)

  - task: HelmInstaller@1
    displayName: "Helm Install"
    inputs:
      helmVersionToInstall: "v3.8.0"

  - script: |
      helm version
      
      echo ""
      
      find
    displayName: "Install NGINX Ingress Controller"
