name: $(Date:yyyy-MM-dd)$(Rev:.r)

trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name:    environment
    type:    string
    default: wasp-sbx-na

variables:
  - template: vars/global.yaml
  - group: azure-credentials-wasp-sandbox

steps:
  - template: common/steps/install-helm.yaml

  - template: common/steps/install-kubectl.yaml

  - template: common/steps/install-terraform-packager.yaml
  
  - template: common/steps/provision-environment.yaml
    parameters:
      environment: ${{ parameters.environment }}

  - template: common/steps/provision-kubernetes-cluster.yaml

# - ARM_CLIENT_ID     -> azurerm-service-principal    / Secret
# - ARM_CLIENT_SECRET -> azurerm-service-principal    / Secret
# - ARM_TENANT_ID     -> azure-subscription-key-vault / ClusterSecretStore
# - ARM_KEYVAULT_NAME -> azure-subscription-key-vault / ClusterSecretStore
  - template: common/steps/install-external-secrets.yaml

  - template: common/steps/install-nginx-ingress-controller.yaml

# - ARM_TENANT_ID       -> azure-config-file / Secret
# - ARM_SUBSCRIPTION_ID -> azure-config-file / Secret
# - ARM_CLIENT_ID       -> azure-config-file / Secret
# - ARM_CLIENT_SECRET   -> azure-config-file / Secret
  - template: common/steps/install-external-dns.yaml

  - template: common/steps/install-cert-manager.yaml

# - ARM_TENANT_ID               -> azure-config-file / Secret
# - ARGOCD_APP_REGISTRATION_ID  -> argocd-cm         / ConfigMap
# - ARGOCD_HOST                 -> argocd-server     / Ingress
# - CERT_MANAGER_CLUSTER_ISSUER -> argocd-server     / Ingress 
  - template: common/steps/install-argocd.yaml
