name: $(Date:yyyy-MM-dd)$(Rev:.r)

trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name:    environment
    type:    string
    default: wasp-sbx-na

variables:
  - template: vars/global.yaml
  - group: azure-credentials-wasp-sandbox

steps:
  - template: common/steps/install-terraform-packager.yaml
    
  - script: |
      env \
        STACK_INSTANCE_NAME=${ENVIRONMENT_NAME} \
        DEBUG=2 \
          stackrun silviosilva/azure-wasp-foundation:0.1.0 plan \
          -var="name=${ENVIRONMENT_NAME}"

    displayName: 'Environment Provision'
    env:
      ENVIRONMENT_NAME:  ${{ parameters.environment }}
      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
      ARM_ACCESS_KEY:    $(ARM_ACCESS_KEY)

  - template: common/steps/install-kubectl.yaml

  - template: common/steps/install-kubernetes-cluster.yaml

  - template: common/steps/install-helm.yaml

  - template: common/steps/install-nginx-ingress-controller.yaml

  - template: common/steps/install-external-dns.yaml

  - template: common/steps/install-httpbin.yaml

  - template: common/steps/install-argocd.yaml
