name: $(Date:yyyy-MM-dd)$(Rev:.r)

trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name:    environment
    type:    string
    default: wasp-sbx-na

variables:
  - template: vars/global.yaml
  - group: azure-credentials-wasp-sandbox

steps:
  - template: common/steps/install-terraform-packager.yaml
    
  - script: |
      env \
        STACK_INSTANCE_NAME=${ENVIRONMENT_NAME} \
        DEBUG=2 \
          stackrun silviosilva/azure-wasp-foundation:0.1.0 plan \
          -var="name=${ENVIRONMENT_NAME}"

    displayName: 'Environment Foundation'
    env:
      ENVIRONMENT_NAME:  ${{ parameters.environment }}
      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
      ARM_ACCESS_KEY:    $(ARM_ACCESS_KEY)

  - template: common/steps/install-kubectl.yaml

  - script: |
      env DEBUG=2 stackrun silviosilva/azure-kubernetes-cluster:3.9.0-wasp-sbx-eus2-blue plan
    displayName: 'AKS Creation'
    env:
      ENVIRONMENT_NAME:  ${{ parameters.environment }}
      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
      ARM_ACCESS_KEY:    $(ARM_ACCESS_KEY)

  - script: |
      mkdir -p ${HOME}/.kube

      env DEBUG=0 stackrun silviosilva/azure-kubernetes-cluster:3.9.0-wasp-sbx-eus2-blue output -raw kubeconfig > ${HOME}/.kube/config

      chmod 0600 ${HOME}/.kube/config

      kubectl config get-contexts
      kubectl get namespaces
    displayName: 'AKS Get Credentials'
    env:
      ENVIRONMENT_NAME:  ${{ parameters.environment }}
      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
      ARM_ACCESS_KEY:    $(ARM_ACCESS_KEY)

  - template: common/steps/install-helm.yaml

  - template: common/steps/install-nginx-ingress-controller.yaml

  - script: |
      install/external-dns/install.sh
    displayName: "Install ExternalDNS"
    env:
      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)

  - template: common/steps/install-httpbin.yaml

  - template: common/steps/install-argocd.yaml
