apiVersion: batch/v1
kind: Job
metadata:
  generateName: curl-test-
  annotations:
    argocd.argoproj.io/hook: PostSync
  #   argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: curl
          image: curlimages/curl
          envFrom:
            - configMapRef:
                name: demo
          command:
            - "curl"
            - "-s"
            - "-X"
            - "GET"
            - "https://httpbin.org/get?execution=$(execution)"
      restartPolicy: Never
  backoffLimit: 2
