{{- range $application := .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $application.name }}
  namespace: {{ ($application.namespace) | default ($.Values.global.namespace) }}

  {{- if $application.finalizers }}
  {{- with $application.finalizers }}
  
  finalizers:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- else }}
  {{- with $.Values.global.finalizers }}

  finalizers:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}

  annotations:
    argocd.argoproj.io/sync-wave: {{ ($application.wave | quote) | default ("100" | quote) }}
spec:
  project: {{ $application.project | default "default" }}

  {{- if $application.source }}
  {{- with $application.source }}
  
  source:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- else }}

  source:
    repoURL: https://github.com/smsilva/wasp-gitops.git
    targetRevision: HEAD
    path: infrastructure/charts/{{ $application.name }}
  {{- end }}

  {{- if $application.destination }}
  {{- with $application.destination }}

  destination:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- else }}
  {{- with $.Values.global.destination }}

  destination:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}

  {{- if $application.syncPolicy }}
  {{- with $application.syncPolicy }}

  syncPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- else }}
  {{- with $.Values.global.syncPolicy }}

  syncPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}

{{- end }}
