annotations:
  configuratorVersion: 1.0.0
apiVersion: v2
appVersion: v2.37.3
dependencies:
- name: common-library
  repository: https://helm-charts.newrelic.com
  version: 1.1.0
description: A Helm chart to deploy Prometheus with New Relic Prometheus Configurator.
keywords:
- newrelic
- prometheus
maintainers:
- name: alvarocabanas
  url: https://github.com/alvarocabanas
- name: carlossscastro
  url: https://github.com/carlossscastro
- name: sigilioso
  url: https://github.com/sigilioso
- name: gsanchezgavier
  url: https://github.com/gsanchezgavier
- name: kang-makes
  url: https://github.com/kang-makes
- name: marcsanmi
  url: https://github.com/marcsanmi
- name: paologallinaharbur
  url: https://github.com/paologallinaharbur
- name: roobre
  url: https://github.com/roobre
name: newrelic-prometheus-agent
type: application
version: 1.0.1
