{{- range $namespace := .Values.namespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $namespace.name }}
  labels:
    {{- if $namespace.istio }}
    istio-injection: enabled
    {{- end }}
    {{- if $.Values.global }}
    {{- with $.Values.global.environment }}
    silvios.me/enviroment-id: "{{ (.id) | default "undefined" }}"
    silvios.me/enviroment-domain: "{{ (.domain) | default "undefined.silvios.me" }}"
    {{- end }}
    {{- end }}
{{- end }}
