{{- range $namespace := .Values.namespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $namespace.name }}
  labels:
    istio-injection: {{ ($namespace.istioInjection) | default "false" }}
{{- end }}
