apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: notifications-controller
  name: argocd-notifications-cm
data:
  context: |
    argocdUrl: {{ .Values.argocdUrl }}

{{- range $key, $value := .Values.services }}
  service.{{ $key }}: |
  {{- toYaml $value | nindent 4 }}
{{- end }}

  subscriptions: |
    {{- toYaml .Values.subscriptions | nindent 4 }}

{{- range $file_name, $_ := $.Files.Glob "files/templates/*.yaml" }}
{{- $file_extension := ext $file_name }}
{{- $base_file_name := base $file_name }}
{{- $template_name := $base_file_name | replace $file_extension "" }}
  template.{{ $template_name }}: |
{{ $.Files.Get $file_name | indent 4 }}
{{- end }}

{{- $trigger_list := dict }}
{{- range $subscription := .Values.subscriptions }}
{{- range $trigger := $subscription.triggers }}
    {{- $_ := set $trigger_list $trigger $trigger }}
{{- end }}
{{- end }}

{{- range $key, $value := $trigger_list }}
{{- $trigger_file_name := printf "%s/%s.yaml" "files/triggers" $key }}
  trigger.{{ $key }}: |
{{ $.Files.Get $trigger_file_name | indent 4 }}
{{- end }}
