piVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
spec:
  project: default

  source:
    path: infrastructure/applications
    repoURL: https://github.com/smsilva/wasp-gitops
    targetRevision: HEAD

  destination:
    name: in-cluster
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
