apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
spec:
  description: Infrastructure

  sourceRepos:
    - https://github.com/smsilva/wasp-gitops
    - git@github.com:smsilva/wasp-gitops.git

  destinations:
    - name: in-cluster
      namespace: '*'
      server: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
