---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-helm
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-kubernetes
  namespace: {{ .Release.Namespace }}
