{{- if eq .Values.global.environment.cluster.ingress.type "azure" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: azure/application-gateway
    cert-manager.io/cluster-issuer: {{ .Values.global.environment.cluster.certificates.type }}-{{ .Values.global.environment.cluster.certificates.server }}-{{ .Values.global.environment.cluster.ingress.type }}
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
    appgw.ingress.kubernetes.io/request-timeout: "70"
    external-dns.alpha.kubernetes.io/ttl: 1m
spec:
  tls:
    - hosts:
        - httpbin.{{ .Values.global.environment.id }}.{{ .Values.global.environment.domain }}
      secretName: ingress-tls-httpbin

  rules:
    - host: httpbin.sandbox.wasp.silvios.me
      http:
        paths:
          - path: /
            backend:
              service:
                name: httpbin
                port:
                  number: 80
            pathType: ImplementationSpecific

    - host: httpbin.{{ .Values.global.environment.id }}.{{ .Values.global.environment.domain }}
      http:
        paths:
          - path: /
            backend:
              service:
                name: httpbin
                port:
                  number: 80
            pathType: ImplementationSpecific
{{- end }}
