{{- if eq .Values.global.environment.cluster.ingress.type "nginx" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin
spec:
  tls:
    - hosts:
        - httpbin.{{ .Values.global.environment.id }}.{{ .Values.global.environment.domain }}
      secretName: ingress-tls-httpbin

  rules:
    - host: httpbin.{{ .Values.global.environment.id }}.{{ .Values.global.environment.domain }}
      http:
        paths:
          - path: /
            backend:
              service:
                name: httpbin
                port:
                  number: 80
            pathType: ImplementationSpecific

  ingressClassName: "nginx"
{{- end }}
