parameters:
  - name:    environment
    type:    string
    default: ""

steps:
  - script: |
      echo "[INFO] Build.DefinitionName...: $(Build.DefinitionName)"
      echo "[INFO] Parameters.Environment.: ${ENVIRONMENT_NAME}"

      echo "##vso[task.setvariable variable=ENVIRONMENT_NAME]${ENVIRONMENT_NAME}"

      env DEBUG=2 stackrun silviosilva/azure-wasp-foundation:0.1.0-${ENVIRONMENT_NAME} \
        apply -auto-approve
    displayName: 'Provision Environment'
    env:
      ENVIRONMENT_NAME:  ${{ parameters.environment }}
      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
      ARM_ACCESS_KEY:    $(ARM_ACCESS_KEY)
