---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    external-dns.alpha.kubernetes.io/target: gateway.{{ .Values.global.environment.id }}.{{ .Values.global.environment.domain }}
spec:
  ingressClassName: {{ .Values.global.environment.cluster.ingress.type }}

  rules:
    - host: echo.{{ .Values.global.environment.id }}.{{ .Values.global.environment.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: httpbin
                port:
                  number: 8000
