---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-for-external-dns-config
  annotations:
    external-dns.alpha.kubernetes.io/target: gateway.{{ .Values.global.environment.id }}.{{ .Values.global.environment.domain }}
spec:
  ingressClassName: {{ .Values.global.environment.cluster.ingress.type }}

  rules:
    - host: echo.{{ .Values.global.environment.id }}.{{ .Values.global.environment.domain }}
      http:
        paths:
          - path: /.well-known/not-used-path/just-for-external-dns-entries
            pathType: Prefix
            backend:
              service: 
                name: non-existent-service
                port:
                  number: 80
