---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin
  namespace: istio-ingress
spec:
  selector:
    istio: ingress

  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - echo.{{ .Values.global.environment.id }}.{{ .Values.global.environment.domain }}

    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: tls-wildcard-full-chain
      hosts:
        - echo.{{ .Values.global.environment.id }}.{{ .Values.global.environment.domain }}
