---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-routes-public
  namespace: example
spec:
  hosts:
    - echo.sandbox.wasp.silvios.me

  gateways:
    - istio-ingress/httpbin

  http:
    - name: httpbin
      headers:
        request:
          add:
            X-A1-origin-1: httpbin-gateway-public

      route:
        - destination:
            host: httpbin.example.svc.cluster.local
            port:
              number: 8000
