apiVersion: v2
appVersion: 1.7.5
dependencies:
- name: common-library
  repository: https://helm-charts.newrelic.com
  version: 1.1.0
description: A Helm chart to deploy the New Relic metadata injection webhook.
home: https://hub.docker.com/r/newrelic/k8s-metadata-injection
icon: https://newrelic.com/assets/newrelic/source/NewRelic-logo-square.svg
keywords:
- infrastructure
- newrelic
- monitoring
maintainers:
- name: alvarocabanas
  url: https://github.com/alvarocabanas
- name: carlossscastro
  url: https://github.com/carlossscastro
- name: gsanchezgavier
  url: https://github.com/gsanchezgavier
- name: kang-makes
  url: https://github.com/kang-makes
- name: marcsanmi
  url: https://github.com/marcsanmi
- name: paologallinaharbur
  url: https://github.com/paologallinaharbur
- name: roobre
  url: https://github.com/roobre
- name: sigilioso
  url: https://github.com/sigilioso
name: nri-metadata-injection
sources:
- https://github.com/newrelic/k8s-metadata-injection
- https://github.com/newrelic/k8s-metadata-injection/tree/master/charts/nri-metadata-injection
version: 4.0.0
